name: Notify Private Repo on PR Merge

on:
  pull_request_target:
    types: [closed]
    branches:
      - mirror

jobs:
  trigger_private_sync:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger private repo sync
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PRIVATE_REPO_PAT }}" \
            https://api.github.com/repos/smarvin/gh-to-gh-roundtrip/dispatches \
            -d '{"event_type": "sync_public_to_private"}'
